<div class="row">
  <div class="col-xs-12 content">

    <section id="description">
      <h2 class="page-header">Korte beschrijving van SchrijfHetInDeSterren.be</h2>
          <p class="">SchrijfHetInDeSterren.be is een onderdeel van <a href="http://spacebillboard.com/" target="_new">SpaceBillboard.com</a>. SpaceBillboard.com is het project waarmee <span class="accent">drie doctoraatsstudenten</span> van de <a href="http://www.kuleuven.be/english" target="_new">KU Leuven</a> hun <span class="accent">ruimtevaartonderzoek willen sponsoren</span> door het <span class="">eerste reclamepaneel in de ruimte</span> te lanceren aan boord van een nieuw type satelliet genaamd CubeSat. Bedrijven en personen van over de hele wereld kunnen hun logo of persoonlijke boodschap de ruimte in brengen als deel van dit paneel, waarna ze voor jaren in een baan om de Aarde blijven. En voor <span class="accent">Valentijn</span> wilden we iets speciaals doen!</p>
      <p>SchrijfHetInDeSterren.be is de Nederlandse versie van onze Valentijnscampagne. Er is ook een versie voor België en een versie voor de rest van de wereld: <a href="http://schrijfhetindesterren.be/" target="_new">http://schrijfhetindesterren.be/</a> en <a href="http://writeitinthestars.com/" target="_new">http://writeitinthestars.com/</a>.
      <p>Je kan meer algemene informatie over dit project vinden op <a href="http://spacebillboard.com/">http://spacebillboard.com/</a> en meer informatie specifiek voor de pers op <a href="http://spacebillboard.com/press">http://spacebillboard.com/press</a>.</p>
    </section>

    <section id="press-releases">
      <h2 class="page-header">Persberichten</h2>

<h3 style="font-family: 'Indie Flower', Arial, Helvetica, sans-serif;">Liefde in de sterren geschreven</h3>

<p><strong>Leuven, België 2 februari, 2015 - </strong> Valentijnsdag, die speciale dag om je liefde aan die ene speciale persoon te verklaren, breidt zijn invloed opnieuw uit. Vanaf nu reikt de valentijnsfeer tot in de sterren, want SchrijfHetInDeSterren.be stelt een unieke manier voor om je liefde to tonen. De website lanceert de valentijnsboodschappen van koppels overal ter wereld in de ruimte.</p>

<strong>Liefde met kosmische afmetingen</strong>
<p>Op valentijnsdag worden wereldwijd miljoenen kaartjes met liefdesboodschappen uitgewisseld. Maar elk jaar opnieuw is het voor velen een grote uitdaging om een origineel cadeau te vinden voor hun geliefde.</p>

<p>De mensen achter SchrijfHetInDeSterren.be moeten dat gevoel kennen, want zij bieden romantische zielen een nooit eerder geziene kans om hun liefde te verklaren. Op hun website (http://schrijfhetindesterren.be), kunnen mensen hun liefde met de hele wereld delen.</p>

<strong>Liefde geschreven in de sterren</strong>
<p>De valentijnboodschappen van SchrijfHetInDeSterren.be worden in de ruimte gebracht aan boord van een satelliet. Eens de valentijnsboodschappen hun baan bereikt hebben, gaan ze elke 90 minuten de wereld rond gaan en vliegen ze uiteindelijk over elk deel van de Aarde.</p>

<p>"Dit is de eerste keer dat je letterlijk je liefde in de sterren kan schrijven.", zegt mede-oprichter van SchrijfHetInDeSterren.be, Maarten Decat. "Het is een fantastische manier om je eeuwigdurende liefde te verklaren, want de boodschappen zullen jaren in de ruimte en op onze website blijven."</p>

<p>De lancering van de boodschappen is momenteel voorzien in het eerste kwartaal van 2016, vanaf de lanceerbasis van Alcântara in Brazilië.</p>

<strong>Een vallende ster</strong>
<p>Na een aantal jaar zal de satelliet met de boodschappen terugkeren in de atmosfeer en opbranden. Maarten Decat: "Op het einde zullen de boodschappen opgaan in een mooie vallende ster, een romantischer einde kunnen we ons niet inbeelden."</p>

<strong>Goeie oude romantiek</strong>
<p>Een valentijnsboodschap in de ruimte betekent niet dat je de goeie oude romantiek van een valentijnskaartje moet missen. Je valentijnsboodschap wordt namelijk ook geplaatst op een gepersonaliseerd en zelf te printen kaartje van één van vijf unieke designs om aan die ene unieke persoon te geven.</p>

<strong style="font-style: italic;">Over SchrijfHetInDeSterren.be</strong>
<p style="font-style: italic;">SchrijfHetInDeSterren.be is het initiatief van drie doctoraatsstudenten van de KU Leuven. Ze hebben SchrijfHetInDeSterren.be gestart als onderdeel van een groter project genaamd SpaceBillboard, een crowdfunding project dat ruimtevaartonderzoek wil steunen door het eerste reclamepaneel ooit in de ruimte te lanceren. Bedrijven en mensen van over de hele wereld kunnen hun logo of boodschap de ruimte in lanceren. SpaceBillboard staat aan het voorfront van innovatieve technologie die het leven op Aarde wil verbeteren, en SchrijfHetInDeSterren.be voegt er romantiek aan toe.</p>

<p style="font-style: italic;">Bezoek onze website op: www.schrijfhetindesterren.be of http://schrijfhetindesterren.be/pers voor extra afbeeldingen en informatie.</p>

<p style="font-style: italic;">Contacteer Tjorven Delabie op tjorven@schrijfhetindesterren.be (+32 498 81 73 70)</p>

<p style="font-style: italic;">Contacteer Maarten Decat op maarten@schrijfhetindesterren.be (+32 472 599 055)</p> 

    </section>

    <section id="fonts">
      <h2 class="page-header">Fonts</h2>

      <p>Onze communicatie gebruikt hoofdzakelijk de volgende twee fonts: <a href="https://www.google.com/fonts/specimen/Indie+Flower" target="_new">Indie Flower</a> en <a href="http://www.dafont.com/denne-at-the-tea-party.font" target="_new">Denne At The Tea Party</a>.</p>

    </section>

    <section id="images">
      <h2 class="page-header">Afbeeldingen</h2>

<div class="row image-wrapper">
  <div class="col-xs-6 image">
    <img src="<?php sbb_echo_theme_file('resources/img/press/team1.jpg'); ?>" class="img-responsive"></img>
    <a href="/sites/all/themes/sbbtheme/resources/img/press/team1-large.jpg" target="_new">Grote versie</a>
  </div>
  <div class="col-xs-6">
    <p>Het team: Maarten, Tjorven en Jeroen</p>
  </div>
</div>

<div class="row image-wrapper">
  <div class="col-xs-6 image">
    <img src="<?php sbb_echo_valentine_theme_file('resources/img/press/cubesat-valentine.jpg'); ?>" class="img-responsive"></img>
    <a href="/sites/all/themes/sbbgeneralvalentinetheme/resources/img/press/cubesat-valentine-large.png" target="_new">Grote versie</a>
  </div>
  <div class="col-xs-6">
    <p>Een gesimuleerde afbeelding van hoe de eerste Valentijnsboodschappen in de ruimte er zullen uitzien. Het paneel aan boord van een CubeSat zal vijftien keer om de Aarde gaan, elke dag opnieuw.</p>
  </div>
</div>

<div class="row image-wrapper">
  <div class="col-xs-6 image">
    <img src="<?php sbb_echo_valentine_theme_file('resources/img/press/cubesat-valentine-with-heart.jpg'); ?>" class="img-responsive"></img>
    <a href="/sites/all/themes/sbbgeneralvalentinetheme/resources/img/press/cubesat-valentine-with-heart-large.png" target="_new">Grote versie</a>
  </div>
  <div class="col-xs-6">
    <p>Een gesimuleerde afbeelding van hoe de eerste Valentijnsboodschappen in de ruimte er zullen uitzien, met toegevoegde figuur van een hartje. Het paneel aan boord van een CubeSat zal vijftien keer om de Aarde gaan, elke dag opnieuw.</p>
  </div>
</div>

<div class="row image-wrapper">
  <div class="col-xs-6 image">
    <img src="<?php sbb_echo_valentine_theme_file('resources/img/press/header.png'); ?>" class="img-responsive"/>
    <a href="<?php sbb_echo_valentine_theme_file('resources/img/press/header.png'); ?>" target="_new">Grote versie</a>
    <a href="<?php sbb_echo_valentine_theme_file('resources/img/press/svg/header.svg'); ?>" target="_new">Schaalbare SVG-versie</a>
  </div>
  <div class="col-xs-6">
    <p>De achtergrond van deze website.</p>
  </div>
</div>

<div class="row image-wrapper">
  <div class="col-xs-6 image">
    <img src="<?php sbb_echo_valentine_theme_file('resources/img/press/logo-be.png'); ?>" class="img-responsive"/>
    <a href="<?php sbb_echo_valentine_theme_file('resources/img/press/svg/logo-be.svg'); ?>" target="_new">Schaalbare SVG-versie</a>
  </div>
  <div class="col-xs-6">
    <p>Het logo van SchrijfHetInDeSterren.be zonder achtergrond.</p>
  </div>
</div>

<div class="row image-wrapper">
  <div class="col-xs-6 image">
    <img src="<?php sbb_echo_valentine_theme_file('resources/img/press/square-1-nl-small.png'); ?>" class="img-responsive"/>
    <a href="<?php sbb_echo_valentine_theme_file('resources/img/press/square-1-nl.png'); ?>" target="_new">Grote versie</a>
  </div>
  <div class="col-xs-6">
    <p>Een vierkante afbeelding die gebruikt kan worden als logo van SchrijfHetInDeSterren.be</p>
  </div>
</div>

<div class="row image-wrapper">
  <div class="col-xs-6 image">
    <img src="<?php sbb_echo_valentine_theme_file('resources/img/press/square-2-nl-small.png'); ?>" class="img-responsive"/>
    <a href="<?php sbb_echo_valentine_theme_file('resources/img/press/square-2-nl.png'); ?>" target="_new">Grote versie</a>
  </div>
  <div class="col-xs-6">
    <p>Een andere vierkante afbeelding die gebruikt kan worden als logo van SchrijfHetInDeSterren.be</p>
  </div>
</div>

<div class="row image-wrapper">
  <div class="col-xs-6 image">
    <img src="<?php sbb_echo_valentine_theme_file('resources/img/press/wide-1-nl-small.png'); ?>" class="img-responsive"/>
    <a href="<?php sbb_echo_valentine_theme_file('resources/img/press/wide-1-nl.png'); ?>" target="_new">Grote versie</a>
  </div>
  <div class="col-xs-6">
    <p>Een brede afbeelding die gebruikt kan worden als logo van SchrijfHetInDeSterren.be</p>
  </div>
</div>

<div class="row image-wrapper">
  <div class="col-xs-6 image">
    <img src="<?php sbb_echo_valentine_theme_file('resources/img/press/wide-2-nl-small.png'); ?>" class="img-responsive"/>
    <a href="<?php sbb_echo_valentine_theme_file('resources/img/press/wide-2-nl.png'); ?>" target="_new">Grote versie</a>
  </div>
  <div class="col-xs-6">
    <p>Een andere brede afbeelding die gebruikt kan worden als logo van SchrijfHetInDeSterren.be</p>
  </div>
</div>

    </section>

    <section id="christmas-cards">
      <h2 class="page-header">Valentijnskaart</h2>

<div class="row image-wrapper">
  <div class="col-xs-6 image">
    <img src="<?php sbb_echo_valentine_theme_file('resources/img/press/valentine-card-example.jpg'); ?>" class="img-responsive"></img>
    <a href="/sites/all/themes/sbbgeneralvalentinetheme/resources/img/press/valentine-card-example-large.jpg" target="_new">Grote versie</a>
  </div>
  <div class="col-xs-6">
    <p>Een voorbeeld van één van onze Valentijnskaarten.</p>
  </div>
</div>

<div class="row image-wrapper">
  <div class="col-xs-6 image">
    <img src="<?php sbb_echo_valentine_theme_file('resources/img/press/large-example-no-arrows-be.png'); ?>" class="img-responsive"></img>
    <a href="/sites/all/themes/sbbgeneralvalentinetheme/resources/img/press/large-example-no-arrows-be-large.png" target="_new">Grote versie</a>
  </div>
  <div class="col-xs-6">
    <p>Een voorbeeld van het ontwerp van één van onze Valentijnskaarten.</p>
  </div>
</div>

<div class="row image-wrapper">
  <div class="col-xs-6 image">
    <img src="<?php sbb_echo_valentine_theme_file('resources/img/press/large-example-be.png'); ?>" class="img-responsive"></img>
    <a href="/sites/all/themes/sbbgeneralvalentinetheme/resources/img/press/large-example-large-be.png" target="_new">Grote versie</a>
  </div>
  <div class="col-xs-6">
    <p>Een voorbeeld van het ontwerp van één van onze Valentijnskaarten.</p>
  </div>
</div>

    </section>

    <section id="faq">
      <h2 class="page-header">FAQ</h2>
      <h4>How worden de Valentijnsboodschapen de ruimte in gelanceerd?</h4>
      <p>De Valentijnsboodschappen zullen gelanceerd worden <a href="http://spacebillboard.com/mission" target="_new">aan boord van een CubeSat</a>.</p>

      <h4>Wanneer worden de Valentijnsboodschappen gelanceerd?</h4>
      <p>Momenteel staan de Valentijnsboodschappen gepland om gelanceerd te worden in het eerste kwartaal van 2016.</p>

      <h4>Zullen we de Valentijnsboodschappen kunnen zien van op de Aarde?</h4>
      <p>Neen. Op een hoogte van 500km en aan een snelheid van 27000 km/u zou je al een heel goeie telescoop moeten hebben om ze te zien, maar ze gaan wel degelijk de ruimte in! Trouwens, hinderende ruimtereclame is tegen de wet en zichtbare Valentijnsboodschappen in de ruimte zouden onze mooie hemel toch maar vervuilen.</p>

      <h4>Wat gaan jullie steunen met de opbrengst?</h4>
      <p>Veel zaken! Ons doel is om ruimtevaartonderzoek aan de KU Leuven te steunen en er staat veel op ons waslijstje. Zo kan extra geld ons bijvoorbeeld toelaten om meer componenten te kopen voor onze studenten. We willen ook een grontstation bouwen zodat die studenten kunnen communiceren met onze CubeSat. En daarnaast willen we gesofisticeerde testopstellingen bouwen om nieuwe technologiën te ontwerpen. Extra fondsen kunnen onze studenten zelfs toelaten om een eigen satelliet te lanceren in de toekomst!</p>

      <h4>Leidt dit project tot ruimtepuin?</h4>
      <p>Neen. De Valentijnsboodschappen zullen zich bevinden aan boord van een nuttige CubeSat op een wetenschappelijke missie. Bovendien vereist de wet van deze satellieten dat ze binnen de 25 jaar uit hun baan om de Aarde gaan. En omdat CubeSats op lage hoogte vliegen, branden ze meestal al op voor het einde van die periode. Nog beter zelfs, CubeSats zouden zelfs kunnen helpen met het opruimen van ruimtepuin!</p>
    </section>

    <section id="contact">
      <h2 class="page-header">Contact</h2>
      <p class="">Je kan ons een e-mail sturen op <a href="mailto:team@schrijfhetindesterren.be">team@schrijfhetindesterren.be</a> of ons bellen op het nummer <strong>0032 472 599 055</strong> (Maarten).</p>
      <p class="">Ons officieel adres is:</p>
      <address>
        <strong>BVBA SpaceBillboard</strong><br>
        Leeuwerikenstraat 45 bus 203<br>
        B-3001 Heverlee<br>
        BTW: BE0555.831.675
      </address>
    </section>

  </div>
</div>
