<div class="row">
  <div class="col-xs-12 content">

    <section id="description">
      <h2 class="page-header">Short description of WriteItInTheStars.com</h2>
      <p class="">WriteItInTheStars.com is a part of <a href="http://spacebillboard.com/" target="_new">SpaceBillboard.com</a>. SpaceBillboard.com is the initiative of <span class="accent">three PhD researchers in engineering</span> of the <a href="http://www.kuleuven.be/english" target="_new">University of Leuven (Belgium)</a> who want to <span class="accent">fund their space research</span> by launching the <span class="">first billboard into space</span>. Companies and people from all over the world can launch their logo or personal message into space on board of that billboard and have it orbit Earth for years to come. And for <span class="accent">Valentine's day</span>, we wanted to do something special!</p>
      <p>WriteItInTheStars.com is the English version of our Valentine campaign. There are also two <span class="accent">websites specifically for Dutch speakers</span> in Belgium and in the Netherlands: <a href="http://schrijfhetindesterren.be/" target="_new">http://schrijfhetindesterren.be/</a> and <a href="http://schrijfhetindesterren.nl/" target="_new">http://schrijfhetindesterren.nl/</a>.
      <p>You can find <span class="accent">more general information</span> on <a href="http://spacebillboard.com/">http://spacebillboard.com/</a> and more press-specific information on <a href="http://spacebillboard.com/press">http://spacebillboard.com/press</a>.</p>
    </section>

    <section id="press-releases">
      <h2 class="page-header">Press releases</h2>

      <h3 class="page-header subsection-header">1. Launch of WriteItInTheStars.com</h3>

<h3 style="font-family: 'Indie Flower', Arial, Helvetica, sans-serif;">Love written in the stars</h3>

<p><strong>Leuven, Belgium, 2015 - </strong> Valentine’s Day, that special day reserved to express your love to that very special person, now truly reaches to the stars. WriteItInTheStars.com presents a unique way to show your love by launching the Valentine messages of people from all around the world in space.</p>

<strong>From space, with love</strong>
<p>On Valentine’s day, millions of cards with messages of love are exchanged all around the world. But every year again, many struggle to find an original gift for their loved ones.</p>

<p>The people behind WriteItInTheStars.com must know that feeling, because they provide romantic souls with a never-seen-before opportunity to express their love. On their website (http://writeitinthestars.com), people can shout out their love for the entire world to hear.</p>

<strong>Love written in the stars</strong>
<p>The Valentine’s messages submitted on WriteItInTheStars.com will be sent into Space on board of a satellite. Once the Valentine messages are in orbit, they will go around the world every 90 minutes and will eventually pass over every place on Earth. </p>

<p>"This is the first time you can literally write your love in the stars.", says co-founder of WriteItInTheStars.com, Maarten Decat. "It’s a great way to express your everlasting love, as the messages will remain in space and on our website for years to come." </p>

<p>The launch of the messages is currently scheduled in the first quarter of 2016 from the launch site of Alcântara in Brazil.</p>

<strong>A shooting star</strong>
<p>After a couple of years, the satellite holding the messages will re-enter into the atmosphere and burn up. As Maarten puts it: "In the end, your message will turn into a beautiful shooting star."</p>

<strong>Old-fashioned romance</strong>
<p>A Valentine message in Space doesn’t mean you have to miss the old-fashioned romance of handing over a real card. Therefore, your Valentine’s message in space comes with a print out version of one of five unique designs that can be downloaded from the WriteitintheStars.com site, to be offered to that precious person you love.</p>

<strong style="font-style: italic;">About WriteItInTheStars.com </strong>
<p style="font-style: italic;">WriteItInTheStars.com is the initiative of three PhD researchers in engineering of the University of Leuven (Belgium). They started WriteItInTheStars.com as part of the larger project called SpaceBillboard, a crowdfunding project that aims to support innovative space research by launching the first billboard into space on board of a new type of satellite called CubeSat. Companies and people from all over the world can launch their logo or personal message into space at affordable cost and have it orbit Earth for years to come. With current sponsors such as Microsoft, SpaceBillboard is at the forefront of building innovative, smart technology platforms that pave the way we learn, live and work tomorrow, and WriteItInTheStars.com adds romance to it.</p>

<p style="font-style: italic;">Visit our website at: www.writeitinthestars.com (or http://writeitinthestars.com/press for extra images and info)</p>

<p style="font-style: italic;">Contact Tjorven Delabie on tjorven@writeitinthestars.com (+32 498 81 73 70)</p>

<p style="font-style: italic;">Contact Maarten Decat on maarten@writeitinthestars.com (+32 472 599 055)</p> 

    </section>

    <section id="fonts">
      <h2 class="page-header">Fonts</h2>

      <p>Our communication mainly employs these two fonts: <a href="https://www.google.com/fonts/specimen/Indie+Flower" target="_new">Indie Flower</a> and <a href="http://www.dafont.com/denne-at-the-tea-party.font" target="_new">Denne At The Tea Party</a>.</p>

    </section>

    <section id="images">
      <h2 class="page-header">Images</h2>

<div class="row image-wrapper">
  <div class="col-xs-6 image">
    <img src="<?php sbb_echo_theme_file('resources/img/press/team1.jpg'); ?>" class="img-responsive"></img>
    <a href="/sites/all/themes/sbbtheme/resources/img/press/team1-large.jpg" target="_new">Large version</a>
  </div>
  <div class="col-xs-6">
    <p>The team: Maarten, Tjorven and Jeroen</p>
  </div>
</div>

<div class="row image-wrapper">
  <div class="col-xs-6 image">
    <img src="<?php sbb_echo_valentine_theme_file('resources/img/press/cubesat-valentine.jpg'); ?>" class="img-responsive"></img>
    <a href="/sites/all/themes/sbbgeneralvalentinetheme/resources/img/press/cubesat-valentine-large.png" target="_new">Large version</a>
  </div>
  <div class="col-xs-6">
    <p>A simulated image of what the Valentine messages in space will look like. The billboard will be on board of a CubeSat and will orbit the Earth fifteen times a day.</p>
  </div>
</div>

<div class="row image-wrapper">
  <div class="col-xs-6 image">
    <img src="<?php sbb_echo_valentine_theme_file('resources/img/press/cubesat-valentine-with-heart.jpg'); ?>" class="img-responsive"></img>
    <a href="/sites/all/themes/sbbgeneralvalentinetheme/resources/img/press/cubesat-valentine-with-heart-large.png" target="_new">Large version</a>
  </div>
  <div class="col-xs-6">
    <p>A simulated image of what the Valentine messages in space will look like, with a heart shape added. The billboard will be on board of a CubeSat and will orbit the Earth fifteen times a day.</p>
  </div>
</div>

<div class="row image-wrapper">
  <div class="col-xs-6 image">
    <img src="<?php sbb_echo_valentine_theme_file('resources/img/press/header.png'); ?>" class="img-responsive"/>
    <a href="<?php sbb_echo_valentine_theme_file('resources/img/press/header.png'); ?>" target="_new">Large version</a>
    <a href="<?php sbb_echo_valentine_theme_file('resources/img/press/svg/header.svg'); ?>" target="_new">Scalable SVG version</a>
  </div>
  <div class="col-xs-6">
    <p>The background image of the WriteItInTheStars.com website.</p>
  </div>
</div>

<div class="row image-wrapper">
  <div class="col-xs-6 image">
    <img src="<?php sbb_echo_valentine_theme_file('resources/img/press/logo-com.png'); ?>" class="img-responsive"/>
    <a href="<?php sbb_echo_valentine_theme_file('resources/img/press/svg/logo-com.svg'); ?>" target="_new">Scalable SVG version</a>
  </div>
  <div class="col-xs-6">
    <p>The logo of WriteItInTheStars.com without background.</p>
  </div>
</div>

<div class="row image-wrapper">
  <div class="col-xs-6 image">
    <img src="<?php sbb_echo_valentine_theme_file('resources/img/press/square-1-small.png'); ?>" class="img-responsive"/>
    <a href="<?php sbb_echo_valentine_theme_file('resources/img/press/square-1.png'); ?>" target="_new">Large version</a>
  </div>
  <div class="col-xs-6">
    <p>A square image that can be used as logo of WriteItInTheStars.com</p>
  </div>
</div>

<div class="row image-wrapper">
  <div class="col-xs-6 image">
    <img src="<?php sbb_echo_valentine_theme_file('resources/img/press/square-2-small.png'); ?>" class="img-responsive"/>
    <a href="<?php sbb_echo_valentine_theme_file('resources/img/press/square-2.png'); ?>" target="_new">Large version</a>
  </div>
  <div class="col-xs-6">
    <p>Another square image that can be used as logo of WriteItInTheStars.com</p>
  </div>
</div>

<div class="row image-wrapper">
  <div class="col-xs-6 image">
    <img src="<?php sbb_echo_valentine_theme_file('resources/img/press/wide-1-small.png'); ?>" class="img-responsive"/>
    <a href="<?php sbb_echo_valentine_theme_file('resources/img/press/wide-1.png'); ?>" target="_new">Large version</a>
  </div>
  <div class="col-xs-6">
    <p>A wide image that can be used as logo of WriteItInTheStars.com</p>
  </div>
</div>

<div class="row image-wrapper">
  <div class="col-xs-6 image">
    <img src="<?php sbb_echo_valentine_theme_file('resources/img/press/wide-2-small.png'); ?>" class="img-responsive"/>
    <a href="<?php sbb_echo_valentine_theme_file('resources/img/press/wide-2.png'); ?>" target="_new">Large version</a>
  </div>
  <div class="col-xs-6">
    <p>Another wide image that can be used as logo of WriteItInTheStars.com</p>
  </div>
</div>

    </section>

    <section id="christmas-cards">
      <h2 class="page-header">Valentine card</h2>

<div class="row image-wrapper">
  <div class="col-xs-6 image">
    <img src="<?php sbb_echo_valentine_theme_file('resources/img/press/valentine-card-example.jpg'); ?>" class="img-responsive"></img>
    <a href="/sites/all/themes/sbbgeneralvalentinetheme/resources/img/press/valentine-card-example-large.jpg" target="_new">Large version</a>
  </div>
  <div class="col-xs-6">
    <p>An example of a printed Valentine card.</p>
  </div>
</div>

    </section>

    <section id="faq">
      <h2 class="page-header">FAQ</h2>
      <h4>How will the Valentine messages be launched into space?</h4>
      <p>The Valentine messages will be <a href="http://spacebillboard.com/mission" target="_new">launched on board of a CubeSat</a>.</p>

      <h4>When will the Valentine messages be launched?</h4>
      <p>The Valentine messages are currently scheduled to be launched in the first quarter of 2016.</p>

      <h4>Will we be able to see the Valentine messages from Earth?</h4>
      <p>No, at an altitude of 500 km and going at a speed of 27000 km/h, you would need to have a pretty good telescope to be able to see them, but they will definitely be in space. By the way, obtrusive space advertising is illegal and visible Valentine messages in space would just litter our beautiful night sky.</p>

      <h4>What will you fund with the money?</h4>
      <p>Lot’s of stuff! Our goal is to fund space research at KU Leuven and we want to do plenty. For example, extra funding will allow us to purchase more components for our Master thesis students. We will also be able to build a ground station so that we can communicate with our CubeSat. We will build more sophisticated test setups and will be able to develop new technologies. Extra funding will even allow us to finance a future launch!</p>

      <h4>Does this project lead to space debris?</h4>
      <p>No. The Valentine messages will be part of a very useful CubeSat performing a scientific mission. The law requires satellites to be removed from their orbit within 25 years. And because CubeSats fly in low orbits, they generally burn up before the end of that period. Even better, CubeSats may in the future help to clear our orbits of space debris!</p>
    </section>

    <section id="contact">
      <h2 class="page-header">Contact</h2>
      <p class="">You can send us an e-mail at <a href="mailto:team@writeitinthestars.com">team@writeitinthestars.com</a> or contact us on the number <strong>0032 472 599 055</strong> (Maarten).</p>
      <p class="">Our official address is:</p>
      <address>
        <strong>BVBA SpaceBillboard</strong><br>
        Leeuwerikenstraat 45 bus 203<br>
        B-3001 Heverlee<br>
        VAT: BE0555.831.675
      </address>
    </section>

  </div>
</div>
