    <section id="description">
      <h2 class="page-header">Short description of SpaceBillboard</h2>

      <p class="">SpaceBillboard is a project set up by researchers from the KU Leuven University of Belgium that will launch the first billboard ever into space. With this project, they want to gather funding for research on CubeSats, a novel and small type of satellites.</p>

      <p>The billboard itself is divided into 400 squares on which companies and people from all over the world can show their logo or personal message. On top of getting their brand or message in outer space, the sponsors of this project help to advance space research, and bring its many benefits a step closer. </p>
    </section>

    <section id="white-paper">
      <h2 class="page-header">White paper</h2>

<div class="row">
  <div class="col-xs-4 image-wrapper">
    <a href="/publications/SpaceBillboard-whitepaper.pdf" target="_new"><img src="/sites/all/themes/sbbtheme/resources/img/press/whitepaper.png" class="img-responsive"></img></a>
  </div>
  <div class="col-xs-8">
    <p>Get the white paper with all information about the project <a href="/publications/SpaceBillboard-whitepaper.pdf" target="_new">here</a>.</p>
  </div>
</div>
    </section>

    <section id="fonts">
      <h2 class="page-header">Fonts</h2>

      <p>Our infographics and other communication mainly employ these two fonts: <a href="https://www.google.com/fonts/specimen/PT+Sans" target="_new">PT Sans</a> and <a href="http://www.dafont.com/robofan-free.font" target="_new">Robofan</a>.</p>

    </section>

    <section id="images">
      <h2 class="page-header">Images</h2>

<div class="row image-wrapper">
  <div class="col-xs-6 image">
    <img src="/sites/all/themes/sbbtheme/resources/img/press/cubesat.png" class="img-responsive"></img>
    <a href="/sites/all/themes/sbbtheme/resources/img/press/cubesat-large.png" target="_new">Large version</a>
  </div>
  <div class="col-xs-6">
    <p>A simulated image of what the first billboard in space will look like. The billboard will be on board of a CubeSat and will orbit the Earth fifteen times a day.</p>
  </div>
</div>

<div class="row image-wrapper">
  <div class="col-xs-6 image">
    <img src="/sites/all/themes/sbbtheme/resources/img/press/logo-space.png" class="img-responsive"/>
    <a href="/sites/all/themes/sbbtheme/resources/img/press/logo-space-full.png" target="_new">Large version</a>
  </div>
  <div class="col-xs-6">
    <p>The background image of the SpaceBillboard website.</p>
  </div>
</div>

<div class="row image-wrapper">
  <div class="col-xs-6 image">
    <img src="/sites/all/themes/sbbtheme/resources/img/press/background.png" class="img-responsive"/>
    <a href="/sites/all/themes/sbbtheme/resources/img/press/background-large.png" target="_new">Large version</a>
  </div>
  <div class="col-xs-6">
    <p>The full background image of the SpaceBillboard website, used in official communication of SpaceBillboard</p>
  </div>
</div>

<div class="row image-wrapper">
  <div class="col-xs-6 image">
    <img src="/sites/all/themes/sbbtheme/resources/img/press/logo.png" class="img-responsive"/>
  </div>
  <div class="col-xs-6">
    <p>The SpaceBillboard logo (white)</p>
  </div>
</div>

<div class="row image-wrapper">
  <div class="col-xs-6 image">
    <img src="/sites/all/themes/sbbtheme/resources/img/press/logo-dark.png" class="img-responsive"/>
  </div>
  <div class="col-xs-6">
    <p>The SpaceBillboard logo (dark grey)</p>
  </div>
</div>

<div class="row image-wrapper">
  <div class="col-xs-6 image">
    <img src="/sites/all/themes/sbbtheme/resources/img/press/rocket.png" class="img-responsive"/>
    <a href="/sites/all/themes/sbbtheme/resources/img/press/rocket.svg" target="_new">SVG version</a>
  </div>
  <div class="col-xs-6">
    <p>A rocket image used in our infographics.</p>
  </div>
</div>
    </section>

    <section id="infographics">
      <h2 class="page-header">Infographics</h2>


<div class="row image-wrapper">
  <div class="col-xs-6 image">
    <img src="/sites/all/themes/sbbtheme/resources/img/press/benefits.png" class="img-responsive"/>
    <a href="/sites/all/themes/sbbtheme/resources/img/press/benefits-large.png" target="_new">Large PNG version</a>
    <a href="/sites/all/themes/sbbtheme/resources/img/press/benefits-xl.png" target="_new">XL PNG version</a><!-- do not put this in the CDN -->
    <a href="/sites/all/themes/sbbtheme/resources/img/press/benefits.pdf" target="_new">Scalable PDF version</a><!-- do not put this in the CDN -->
    <a href="/sites/all/themes/sbbtheme/resources/img/press/benefits.ai" target="_new">Adobe Illustrator source</a><!-- do not put this in the CDN -->
  </div>
  <div class="col-xs-6">
    <p>Infographic which introduces CubeSats and highlights their potential. Compared to typical satellites (which are the size of a minivan), CubeSats are smaller, lighter and consume significantly less power. Their design philosophy is also different. Conventional satellites are built with expensive custom-made components and are preferably built with components that have already proven to work in space before. Because of this, conventional satellites often use older technology. CubeSats on the other hand can use commercially available components, like the ones in your smartphone. They can use the latest state-of-the-art technology and despite being smaller, they can give some bigger satellites a run for their money. Thanks to these differences, CubeSats can be built faster and for less money. As a result, CubeSats enable space research at non-commercial organizations such as universities and push space research in higher gear, which leads to amazing possibilities.</p>
    <p>The source requires the fonts <a href="https://www.google.com/fonts/specimen/PT+Sans" target="_new">PT Sans</a> and <a href="http://www.dafont.com/robofan-free.font" target="_new">Robofan</a>.
  </div>
</div>

<div class="row image-wrapper">
  <div class="col-xs-6 image">
    <img src="/sites/all/themes/sbbtheme/resources/img/press/render.png" class="img-responsive"/>
    <a href="/sites/all/themes/sbbtheme/resources/img/press/render-large.png" target="_new">Large version</a>
  </div>
  <div class="col-xs-6">
    <p>An &quot;exploded view&quot; of a typical CubeSat. The solar panels cover the CubeSat on the outside and an antenna allows to communicate with a ground station. Inside the CubeSat is a stack of green electronic print plates. Depending on its mission, the CubeSat needs several &quot;subsystems&quot;. On top of the print plates is the payload. This particular CubeSat has a camera to take pictures of the Earth.</p>
  </div>
</div>

<div class="row image-wrapper">
  <div class="col-xs-6 image">
    <img src="/sites/all/themes/sbbtheme/resources/img/press/render-labeled.png" class="img-responsive"/>
    <a href="/sites/all/themes/sbbtheme/resources/img/press/render-labeled-large.png" target="_new">Large version</a>
  </div>
  <div class="col-xs-6">
    <p>The same &quot;Exploded view&quot; of a typical CubeSat, with names assigned to the different parts.</p>
  </div>
</div>

<div class="row image-wrapper">
  <div class="col-xs-6 image">
    <img src="/sites/all/themes/sbbtheme/resources/img/press/height-overview.jpg" class="img-responsive"/>
    <a href="/sites/all/themes/sbbtheme/resources/img/press/height-overview-large.png" target="_new">Large version</a>
  </div>
  <div class="col-xs-6">
    <p>Infographic showing the altitude of SpaceBillboard compared to the altitude of well-known other objects. The Karman Line, which is often taken as the boundary of space is well below us.</p>
  </div>
</div>

<div class="row image-wrapper">
  <div class="col-xs-6 image">
    <img src="/sites/all/themes/sbbtheme/resources/img/press/mission-statement.jpg" class="img-responsive"/>
    <a href="/sites/all/themes/sbbtheme/resources/img/press/mission-statement-large.png" target="_new">Large version</a>
  </div>
  <div class="col-xs-6">
    <p>Our mission statement</p>
  </div>
</div>

<div class="row image-wrapper">
  <div class="col-xs-6 image">
    <img src="/sites/all/themes/sbbtheme/resources/img/press/superlative-advertising.png" class="img-responsive"/>
    <a href="/sites/all/themes/sbbtheme/resources/img/press/superlative-advertising-large.png" target="_new">Large version</a>
    <a href="/sites/all/themes/sbbtheme/resources/img/press/superlative-advertising-xl.png" target="_new">XL version</a><!-- do not put this in the CDN -->
    <a href="/sites/all/themes/sbbtheme/resources/img/press/superlative-advertising.pdf" target="_new">Scalable PDF version</a><!-- do not put this in the CDN -->
    <a href="/sites/all/themes/sbbtheme/resources/img/press/superlative-advertising.ai" target="_new">Adobe Illustrator source</a><!-- do not put this in the CDN -->
  </div>
  <div class="col-xs-6">
    <p>Extreme facts about SpaceBillboard: SpaceBillboard will be the first billboard in space, SpaceBillboard will be the highest billboard ever, SpaceBillboard will be the fastest billboard ever and SpaceBillboard will be the only billboard to literally take its advertisements around the world, 15 times a day.</p>
    <p>The source requires the fonts <a href="https://www.google.com/fonts/specimen/PT+Sans" target="_new">PT Sans</a> and <a href="http://www.dafont.com/robofan-free.font" target="_new">Robofan</a>.
  </div>
</div>
    </section>

    <section id="videos">
      <h2 class="page-header">Videos</h2>
<div class="row video-wrapper">
  <div class="col-xs-12">
    <iframe src="//player.vimeo.com/video/80134768?title=0&amp;byline=0&amp;portrait=0&amp;autoplay=0" width="500" height="281" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
    <a href="http://vimeo.com/spacebillboard/promo" target="_new">At Vimeo</a>
  </div>
</div>
    </section>

    <section id="faq">
      <h2 class="page-header">FAQ</h2>

      <h4>How will the billboard be launched into space?</h4>
      <p>The billboard will be launched on board of a CubeSat.</p>

      <h4>When will the billboard be launched?</h4>
      <p>The billboard is currently scheduled to be launched in the first quarter of 2016.</p>

      <h4>Will we be able to see the billboard from Earth?</h4>
      <p>No, at an altitude of 500 km and going at a speed of 27000 km/h, you would need to have a pretty good telescope to be able to see it. Our goal with the billboard is to give our sponsors and our project visibility here on Earth. By the way, obtrusive space advertising is illegal and a visible billboard in space would just litter our beautiful night sky.</p>

      <h4>What will you fund with the money?</h4>
      <p>Lot’s of stuff! Our goal is to fund space research at KU Leuven and we want to do plenty. For example, extra funding will allow us to purchase more components for our Master thesis students. We will also be able to build a ground station so that we can communicate with our CubeSat. We will build more sophisticated test setups and will be able to develop new technologies. Extra funding will even allow us to finance a future launch!</p>

      <h4>Does this project lead to space debris?</h4>
      <p>No. The billboard will be part of a very useful CubeSat performing a scientific mission. The law requires satellites to be removed from their orbit within 25 years. And because CubeSats fly in low orbits, they generally burn up before the end of that period. Even better, CubeSats may in the future help to clear our orbits of space debris!</p>
    </section>
