<footer class="footer">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-sm-8 col-xs-12">
        <div class="row">
          <div class="">
            <div class="footer-logo">Writeitinthestars.com</div>   
          </div>
        </div>
        <div class="row hidden-xs">
          <div class="">
          </div> 
        </div>
      </div>
      <div class="col-md-6 col-sm-4 hidden-xs">
        <div class="supported-by">
          <p>Proudly hosted by <a href="https://azure.microsoft.com/" target="_new">Microsoft Azure</p>
        </div>
        <?php //print render($page['footer']); ?>
      </div>
    </div>  
  </div>
</footer>
