<footer class="footer">
  <div class="container">
    <div class="row">
      <div class="col-md-2 col-sm-3 col-xs-12">
      </div>
      <div class="col-md-4 col-sm-5 col-xs-12">
        <div class="row">
          <div class="">
            <div class="footer-logo">SpaceBillboard.com</div>   
          </div>
        </div>
      </div>
      <div class="col-md-6 col-sm-4 hidden-xs">
        <div class="supported-by"> </div>
        <div class="region region-footer">
          <a href="/the-team">Who are we?</a> - <a href="press">Press</a> - <a href="contact">Contact</a> - <a href="/disclaimer">Disclaimer</a> - <a href="/follow">Follow</a><p></p>
        </div>
        <?php //print render($page['footer']); ?>
      </div>
    </div>  
  </div>
</footer>
