<h1 class="real-page-title page-header">For advertisers</h1>

<div class="row">
  <div class="col-md-3 hidden-xs hidden-sm scrollspy-target">

    <ul class="nav nav-list sbb-sidenav" data-spy="affix" data-offset-top="286" data-offset-bottom="270">
      <li class="active"><a href="#superlatives" class="nav-link"><i></i> <span>Superlatives</span></a></li>
      <li><a href="#in-for-you" class="nav-link"><i></i> <span>What's in it for you?</span></a></li>
      <li><a href="#the-campaign" class="nav-link"><i></i> <span>The campaign</span></a></li>
      <li><a href="#why-cubesats" class="nav-link"><i></i> <span>Why CubeSats?</span></a></li>
      <li><a href="#how-does-it-work" class="nav-link"><i></i> <span>How does it work?</span></a></li>
      <li><a href="#interested" class="nav-link"><i></i> <span>Interested?</span></a></li>
      <li>
        <?php include_once(drupal_get_path('theme', 'sbbtheme') . '/featured-sponsor/featured-sponsor.inc.php'); sbb_generate_featured_sponsor(); ?>
      </li>
    </ul>

  </div>
  <div class="col-md-9 content">

    <section id="overview">
      <p class="description">SpaceBillboard sells advertisement space on a billboard that will be launched into space on board of a satellite. This will be the <span class="accent">first advertisement platform ever to pass the boundary of space</span>. The revenues of this project will be used to <span class="accent">sponsor space research</span> at the University of Leuven. But this is <span class="accent">not just charity</span>. This unique story will go around the world as well. Read on to see what's in it for our sponsors.</p>

      <p class="description accent">Submissions were closed on July 1st 2015.</p>
      <p class="description accent">We're getting the billboard ready for the launch now!</p>
    </section>



    <section id="superlatives">
      <h2 class="page-header">SpaceBillboard, superlative advertising</h2>

      <p class="description">Once the billboard is in orbit, it will be a billboard of firsts and extremes:</p>

      <div class="row info">
        <div class="col-md-4 text md-pull-right">
          <h1>The first</h1>
          <p class="explanation-text">The billboard on board of a CubeSat will be the first in <span class="accent">space</span>.</p>
        </div>
        <div class="col-md-8">
          <div class="img" style="background-image: url(<?php sbb_echo_theme_file('resources/img/our-mission/first-total.png'); ?>);"></div>
        </div>
      </div> <!-- </info> -->

      <div class="row info">
        <div class="col-md-4 text md-pull-right">
          <h1>The highest</h1>
          <p class="explanation-text">The billboard will orbit the Earth at an altitude of <span class="accent">500 km</span> or <span class="accent">310 mi</span>. That's about 1543 Eiffel towers and 130km above the ISS.</p>
        </div>
        <div class="col-md-8 col-xs-12">
          <div class="row">
            <div class="col-xs-6 col-sm-4 col-sm-offset-2 col-md-5 col-md-offset-1">
              <div class="explanation">
                1543 Eiffel Towers
              </div>
            </div>
            <div class="col-xs-6 col-sm-4 col-md-5">
              <div class="explanation">
                130 km above the ISS
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-xs-6 col-sm-4 col-sm-offset-2 col-md-5 col-md-offset-1">
              <div class="img" style="background-image: url(<?php sbb_echo_theme_file('resources/img/our-mission/highest-eiffel.png'); ?>);"></div>
            </div>
            <div class="col-xs-6 col-sm-4 col-md-5">
              <div class="img" style="background-image: url(<?php sbb_echo_theme_file('resources/img/our-mission/highest-total.png'); ?>);"></div>
            </div>
          </div>        
        </div>
      </div> <!-- </info> -->


      <div class="row info">
        <div class="col-md-4 text md-pull-right">
          <h1>The furthest</h1>
          <p class="explanation-text">The billboard will go <span class="accent">around the world in 90 minutes</span> and cover a total distance of <span class="accent">660,000 km/day</span> or <span class="accent">410,000 mi/day</span>. That's about 15,600 marathons each day. Every day again.</p>
        </div>
        <div class="col-md-8">
          <div class="row">
            <div class="col-xs-6 col-sm-4 col-sm-offset-2 col-md-5 col-md-offset-1">
              <div class="explanation">
                Every 90 minutes around the world
              </div>
            </div>
            <div class="col-xs-6 col-sm-4 col-md-5">
              <div class="explanation">
                15,600 marathons/day
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-xs-6 col-sm-4 col-sm-offset-2 col-md-5 col-md-offset-1">
              <div class="img" style="background-image: url(<?php sbb_echo_theme_file('resources/img/our-mission/furthest-orbit.png'); ?>);"></div>
            </div>
            <div class="col-xs-6 col-sm-4 col-md-5">
              <div class="img" style="background-image: url(<?php sbb_echo_theme_file('resources/img/our-mission/furthest-runner.png'); ?>);"></div>
            </div>
          </div>        
        </div>
      </div> <!-- </info> -->

      <div class="row info">
        <div class="col-md-4 text md-pull-right">
          <h1>The fastest</h1>
          <p class="explanation-text">The billboard will orbit the Earth at a speed of <span class="accent">27,400 km/h</span> or <span class="accent">17,030 mph</span>. That's 72 times the top speed of a F1 car and 22 times the speed of a bullet.</p>
        </div>
        <div class="col-md-8">
          <div class="row">
            <div class="col-xs-6 col-sm-4 col-sm-offset-2 col-md-5 col-md-offset-1">
              <div class="explanation">
                72 times the top speed of a F1 car
              </div>
            </div>
            <div class="col-xs-6 col-sm-4 col-md-5">
              <div class="explanation">
                22 times the speed of a bullet
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-xs-6 col-sm-4 col-sm-offset-2 col-md-5 col-md-offset-1">
              <div class="img" style="background-image: url(<?php sbb_echo_theme_file('resources/img/our-mission/fastest-f1.png'); ?>);"></div>
            </div>
            <div class="col-xs-6 col-sm-4 col-md-5">
              <div class="img" style="background-image: url(<?php sbb_echo_theme_file('resources/img/our-mission/fastest-many-bullets.png'); ?>);"></div>
            </div>
          </div>        
        </div>
      </div> <!-- </info> -->

    </section>

    <div class="visible-xs visible-sm">
      <?php sbb_generate_horizontal_featured_sponsor(); ?>
    </div>

    <section id="in-for-you">
      <h2 class="page-header">What’s in it for you?</h2>

      <div class="earth-bg">
        <div class="row">
          <div class="reason col-md-6 col-sm-6 col-xs-6 text-left"><h4><a href="#global-visibility">Global Visibility</a></h4></div>
          <div class="reason col-md-6 col-sm-6 col-xs-6 text-right"><h4><a href="#support-innovation">Support Innovation</a></h4></div>
        </div>
        <div class="row">
          <div class="reason col-md-6 col-sm-6 col-xs-6 text-left"><h4><a href="#digital-advertising">Digital Advertising</a></h4></div>
          <div class="reason col-md-6 col-sm-6 col-xs-6 text-right"><h4><a href="#low-cost-and-effort">Low cost and effort</a></h4></div>
        </div>
        <div class="row">
          <div class="reason col-md-6 col-sm-6 col-xs-6 text-left"><h4><a href="#marketing-first">Marketing First</a></h4></div>
          <div class="reason col-md-6 col-sm-6 col-xs-6 text-right"><h4><a href="#space-is-awesome">Space is awesome!</a></h4></div>
        </div>
      </div>

      <div class="row info">
        <div class="col-md-9 text md-pull-right">
          <a id="global-visibility"></a>
          <h2>1. Global visibility</h2>
          <h4>A lot of visitors...</h4>
          <p class="explanation-text">The SpaceBillboard project is coupled with an <span class="accent">extensive media campaign</span>. We use <span class="accent">professional PR services</span> to reach a large audience through <span class="accent">both conventional as social media</span>.</p>
          <h4>...who pay attention to your ad.</h4>
          <p class="explanation-text">The campaign will inform people about our project and bring them to our website, where the billboard with your ad will be clearly visible. As opposed to conventional on-line advertisements, <span class="accent">the billboard is the most important content of our website</span> and gets a very prominent and visible place.</p>
        </div>
        <div class="col-md-3">
          <div class="img" style="background-image: url(<?php sbb_echo_theme_file('resources/img/for-advertisers/global.png'); ?>);"></div>
        </div>
      </div> <!-- </info> -->

      <div class="row info">
        <div class="col-md-9 text md-pull-right">
          <a id="digital-advertising"></a>
          <h2>2. Digital advertising</h2>
          <h4>On-line and engaging</h4>
          <p class="explanation-text">People increasingly spend time on-line. It is therefore important for companies to connect with their customers on-line. By advertising on SpaceBillboard, <span class="accent">you engage in an innovative way</span> to reach your consumer on-line. Visitors who are interested in your ad can immediately click through to your company website or a webpage you have set up specifically for this project.</p>
          <h4>Social media</h4>
          <p class="explanation-text">Our media campaign also has a very <span class="accent">strong social media aspect</span>. Advertising on our billboard could very well create a buzz around your company on social media.</p>
        </div>
        <div class="col-md-3">
          <div class="img" style="background-image: url(<?php sbb_echo_theme_file('resources/img/for-advertisers/smartphone.png'); ?>);"></div>
        </div>
      </div> <!-- </info> -->

      <div class="row info">
        <div class="col-md-9 text md-pull-right">
          <a id="marketing-first"></a>
          <h2>3. Marketing first</h2>
          <p class="explanation-text"><span class="accent">SpaceBillboard is a marketing first in many ways.</span> Odds are that people will remember it and refer to it in years to come, especially when new kinds of space marketing pop up. And the good news? They will still be able to see that you advertised on it, because our site will remain on-line <span class="accent">for at least 10 years</span>.</p>
        </div>
        <div class="col-md-3">
          <div class="img" style="background-image: url(<?php sbb_echo_theme_file('resources/img/for-advertisers/first.png'); ?>);"></div>
        </div>
      </div> <!-- </info> -->

      <div class="row info">
        <div class="col-md-9 text md-pull-right">
          <a id="support-innovation"></a>
          <h2>4. Support innovation</h2>
          <p class="explanation-text">By advertising on the billboard, you <span class="accent">help space research to advance</span> further. More precisely, the revenues of SpaceBillboard will be used to support the research on <span class="accent">CubeSats</span>. These small satellites offer tremendous opportunities in the adventurous field of space research.</p>
          <h4></h4>
          <p class="explanation-text"></p>
        </div>
        <div class="col-md-3">
          <div class="img" style="background-image: url(<?php sbb_echo_theme_file('resources/img/for-advertisers/innovation.png'); ?>);"></div>
        </div>
      </div> <!-- </info> -->

      <div class="row info">
        <div class="col-md-9 text md-pull-right">
          <a id="low-cost-and-effort"></a>
          <h2>5. Low cost and effort</h2>
          <h4>Low cost</h4>
          <p class="explanation-text">SpaceBillboard is a unique project that will last for at least a decade, but we still choose to <span class="accent">keep the cost low</span>.</p>
          <h4>Sit back and relax</h4>
          <p class="explanation-text">Setting up a marketing campaign can take a lot of money and manpower, but advertising on the SpaceBillboard is <a class="scroll" href="#how-does-it-work">almost effortless</a>. All you need to do is select an image you would like on the Billboard and a link that viewers go to when they click your ad. You can of course put in more effort and build your own campaign around your space endeavors.</p>
        </div>
        <div class="col-md-3">
          <div class="img" style="background-image: url(<?php sbb_echo_theme_file('resources/img/for-advertisers/cheap.png'); ?>);"></div>
        </div>
      </div> <!-- </info> -->

      <div class="row info">
        <div class="col-md-9 text md-pull-right">
          <a id="space-is-awesome"></a>
          <h2>6. Space is awesome!</h2>
          <p class="explanation-text">An advertisement spot on the billboard comes with <span class="accent">great bragging rights</span>!</p>
        </div>
        <div class="col-md-3">
          <div class="img" style="background-image: url(<?php sbb_echo_theme_file('resources/img/for-advertisers/cool.png'); ?>);"></div>
        </div>
      </div> <!-- </info> -->

    </section>

    <section id="the-campaign">
      <h2 class="page-header">The Campaign</h2>

      <h3>Conventional Media Campaign</h3>

      <h4>Press releases</h4>

      <p>Using professional PR services, SpaceBillboard will be brought into the attention of the media by sending out press releases to <span class="accent">magazines, newspapers, television channels, radio channels and blogs</span>.  This way, we will maximize the outreach and impact of our campaign. Press releases will be sent out in various stages of the project, such as the start of the project, the launch of the satellite, etc. Check out <a href="/press-coverage">the press coverage page</a> for an overview of what we have achieved so far.</p>

      <h4>This project will soar. Period.</h4>
      <p>Because of the <span class="accent">novelty of this project</span>, these press releases are sure to be published and receive a lot of attention. Space projects such as Felix Baumgartner’s skydiving and the Mars One project <span class="accent">inspire people</span> and spark the imagination. The first billboard in space will draw the curiosity and draw viewers to our site and your advertisement.</p>

      <h4>A story of many angles.</h4>
      <p>An important advantage of our story is that it has multiple interesting angles, making it interesting for media catering to different audiences, ranging from <span class="accent">technical and scientific media</span>, over <span class="accent">mainstream media</span> to <span class="accent">economic and entrepreneurial media</span>.</p>

      <img src="<?php sbb_echo_theme_file('resources/img/for-advertisers/media-plan.png'); ?>" class="img-responsive"></img>

      <h3>Social Media Campaign: win a trip to the launch!</h3>

      <p>Users of social networks such as Facebook, Twitter, Google+ can <span class="accent">win a trip to the launch</span>. This way, more people get to know about our project and we create a word-of-mouth campaign.</p>

    </section>

    <div class="visible-xs visible-sm">
      <?php sbb_generate_horizontal_featured_sponsor(); ?>
    </div>

    <section id="why-cubesats">
      <h2 class="page-header">Why support CubeSat research?</h2>
        <p>With SpaceBillboard, we want to support CubeSat research. Why? Well, because of the many advantages CubeSats offer us and we strongly believe that <span class="accent">this research deserves more attention and funding</span>. Read all about CubeSats on <a href="/mission">Our Mission</a>.</p>
    </section>

    <section id="how-does-it-work">
      <h2 class="page-header">How does it work?</h2>

      <h3>The procedure</h3>

      <p>To get your advertisement on SpaceBillboard, you can select your preferred squares on <a href="/">the billboard</a> or go to the <a href="/buy">Buy squares page</a>. Every square is 30x30 px large with 4px between squares. On the contact form, you provide us with your information, after which we will contact you as soon as possible. In the end, we need the following from you:
      <ul>          
        <li>The image you want to put on the billboard and which will go in space.</li>
        <li>A link to which visitors will be guided if they click your advertisement.</li>
        <li>A message that will be displayed, together with your ad, in the ‘featured sponsor’ square. </li>
      </ul>
      <p>Once the contract is signed and we have received your initial payment, your advertisement is part of the first billboard in space!</p>

      <h3>Positioning on the billboard</h3>

      <p>Your advertisement will be added to the billboard on the positions as indicated at the start of the procedure. However, it can be the case that multiple parties opt for the same square. In this case, the first party of which we receive payment gets the square. The other parties will be notified and will be given the opportunity to choose another position.</p>
<p>In order to get an optimal arrangement of ads, it may be necessary to reposition some ads on the billboard. Of course we will avoid this if not strictly necessary.</p>

    </section>

    <section id="interested">
      <h2 class="page-header">Interested?</h2>

      <p><a href="/buy">Click here to buy squares</a> or click <a href="/">the billboard</a> if you prefer certain squares!.</p>

    </section>

  </div>
</div>
