<p>SpaceBillboard.com is an initiative of young Belgian entrepreneurs and researchers of the University of Leuven. We have joined forces with experienced PR-professionals in order to launch the first billboard into Space.</p>

<h2 class="page-header">The team</h2>

<div class="row odd"><div class="row-inner">
  <div class="span3 text-center"><img src="<?php sbb_echo_theme_file('resources/img/who-are-we/boy-cropped.gif'); ?>" width="200" height="200" class="img-polaroid" alt=""  data-thmr="thmr_20" /></div>
  <div class="span9">
    <h3>Tjorven</h3>
    <p>Tjorven is ... </p>
  </div>
</div></div>

<div class="row top-buffer even"><div class="row-inner">
  <div class="span3 text-center"><img src="<?php sbb_echo_theme_file('resources/img/who-are-we/girl-cropped.jpg'); ?>" width="200" height="200" class="img-polaroid" alt=""  data-thmr="thmr_20" /></div>
  <div class="span9">
    <h3>Sofie</h3>
    <p>Sofie is ...</p>
  </div>
</div></div>

<div class="row top-buffer odd"><div class="row-inner">
  <div class="span3 text-center"><img src="<?php sbb_echo_theme_file('resources/img/who-are-we/boy-cropped.gif'); ?>" width="200" height="200" class="img-polaroid" alt=""  data-thmr="thmr_20" /></div>
  <div class="span9">
    <h3>Jeroen</h3>
    <p>Jeroen is ...</p>
  </div>
</div></div>

<div class="row top-buffer even"><div class="row-inner">
  <div class="span3 text-center"><img src="<?php sbb_echo_theme_file('resources/img/who-are-we/boy-cropped.gif'); ?>" width="200" height="200" class="img-polaroid" alt=""  data-thmr="thmr_20" /></div>
  <div class="span9">
    <h3>Maarten</h3>
    <p>Maarten is...</p>
  </div>
</div></div>
