<?php

/**
 * Implements hook_menu(). Does the URL binding.
 */
function sbbcompanies_menu() {
  $items = array();
  
  $items['companies/%'] = array(
    'title' => '',
    'page callback' => 'sbbcompanies_redirect_company',
    'page arguments' => array(1),
    'access callback' => true,
    'type' => MENU_CALLBACK
  );
  
  $items['company-list-json'] = array(
    'title' => '',
    'page callback' => 'company_list_json',
    'access callback' => true,
    'type' => MENU_CALLBACK,
    'delivery callback' => 'drupal_json_output' 
  );

  return $items;
}

function sbbcompanies_redirect_company($company = 'company') {
  module_load_include('inc.php', 'sbbcompanies', 'classes/CompanyHelperFunctions');
  // only log in valid URLs
  if(CompanyHelperFunctions::companyExists($company)) {
    watchdog('sbbcompanies', "Company URL requested: $company");
    user_cookie_save(array("company" => $company));
  } else {
    watchdog('sbbcompanies', "Non-existing URL requested: $company");
  }
  drupal_goto();
}

function company_list_json() {
  module_load_include('inc.php', 'sbbcompanies', 'classes/CompanyHelperFunctions');
  $urls = CompanyHelperFunctions::allCompanyURLs();
  return array("urls" => $urls);
}

/**
 *  Implements hook_init().
 */
function sbbcompanies_init() {
  $path = request_path();
  if(user_is_anonymous()) { // only do this for anonymous users, the rest is handled by Drupal itself
    if ($path == "") {
      // we are on the front page, do nothing here: the page itself manages this
      return;
    } elseif (substr($path, 0, 4) == 'user') {
      // we should still be able to log in and stuff
      return;
    } elseif (substr($path, 0, 10) == 'companies/') {
      // the company URL should always be accessible
      return; 
    } elseif (substr($path, 0, 9) == 'messages/') {
      // the company URL should always be accessible
      return; 
    } elseif (substr($path, 0, 5) == 'press') {
      // the press URL should always be accessible
      return; 
    } elseif (strstr($path, 'coming-soon-contact-form') || strstr($path, 'node/29')) {
      // for the contact form on the coming soon page
      return; 
    } elseif (strstr($path, 'coming-soon-buy-form') || strstr($path, 'node/33')) {
      // for the buy form on the coming soon page
      return; 
    } elseif (substr($path, 0, 4) == 'blog') {
      // for the blog page on Coming Soon
      return; 
    } elseif (substr($path, 0, 6) == 'httprl') {
      // for the HTTPRL module
      return; 
    } else {
      // only include CompanyHelperFunctions here
      module_load_include('inc.php', 'sbbcompanies', 'classes/CompanyHelperFunctions');
      if (CompanyHelperFunctions::isCompanyUserLoggedIn()) {
        // company users can access anything, just log the access
        $company = CompanyHelperFunctions::getCurrentCompany();
        $company = $company['name'];
        watchdog('sbbcompanies', "Granted access to $company");
        return;
      } else {
        // in any other case: redirect to home page to see the "Coming soon"
        watchdog('sbbcompanies', "Access denied: no company user logged in");
        drupal_goto();
      }
    }
  }
}
